name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK and Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          maven-version: '3.9.6'

      - name: Print Java and Maven Versions
        run: |
          echo "Java Version: $(java -version)"
          echo "Maven Version: $(mvn -v)"

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/lucbod/languageapp_backend:latest .
          docker push ghcr.io/lucbod/languageapp_backend:latest  

      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          wait-for-success: true
          registry-secret: ${{ secrets.CR_PAT }}
